FROM harbor.corp.motiv/docker/library/node:22.9.0-alpine AS base

FROM base AS builder
ARG DEPS_IMAGE
WORKDIR /app

COPY --from=${DEPS_IMAGE} /app/node_modules ./node_modules
COPY . .

RUN yarn nx build data-loader

FROM base AS runner
ARG DEPS_IMAGE
WORKDIR /app
USER 1000

COPY --chown=1000 --from=builder /app/dist/apps/data-loader/ .                                        
COPY --chown=1000 --from=${DEPS_IMAGE} /app/node_modules ./node_modules

CMD ["node", "main.js"] 
