FROM node:22.2.0-alpine AS base
FROM base AS deps
WORKDIR /app
COPY package.json yarn.lock ./
# RUN yarn config set registry http://localhost:4873
RUN yarn config set network-timeout 600000
#RUN yarn
RUN --mount=type=cache,target=/usr/local/share/.cache yarn install 
RUN yarn cache clean
