{{- range  $app := $.Values.apps }}
{{- if $app.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-{{ $app.name }}"
  labels:
    app: "{{ $.Release.Name }}-{{ $app.name }}"
spec:
  selector:
    app: "{{ $.Release.Name }}-{{ $app.name }}"
  ports:
  - name: http
    port: {{ $app.port }}
    protocol: TCP
  type: ClusterIP
{{- end }}
{{- end }}
