{{- range  $app := $.Values.apps }}
{{- with $app.serviceMonitor -}}
{{- if .enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ $.Release.Name }}-{{ $app.name }}"
  {{- with $app.serviceMonitor.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    app: "{{ $.Release.Name }}-{{ $app.name }}"
{{ $app.serviceMonitor.labels | toYaml | indent 4 }}
spec:
  selector:
    matchLabels:
      app: "{{ $.Release.Name }}-{{ $app.name }}"
  endpoints:
    - port: {{ $app.serviceMonitor.port |default "http" }}
      path: {{ $app.serviceMonitor.path |default "/metrics" }}
      interval: {{ $app.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ $app.serviceMonitor.scrapeTimeout | default "30s" }}
{{- end }}
{{- end -}}
{{- end }}
