{
 "title": "Apollo GraphQL Metrics",
 "description": "Apollo GraphQL metrics. Mutations/errors/operations.",
 "tags": [
  "graphql",
  "prometheus",
  "nestjs"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(graphql_queries_responded, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "description": "логи бэка и микросервиса",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{api=\"api\", rmq=\"rmq\"} |= ``"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client List",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "command": "clientList", "type": "command" }
   ]
  },
  {
   "title": "SLOWLOG",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "command": "slowlogGet", "streamingDataType": "TimeSeries", "type": "command" }
   ]
  },
  { "title": "PSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Users",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM \"user\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Товары",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(id) FROM product" }
   ]
  },
  {
   "title": "Категории",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM category LIMIT 50 "
    }
   ]
  },
  { "title": "Health Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Memory",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_external_memory_bytes) / (16 * 1024 * 1024 * 1024) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "CPU",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto__" }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_resolved{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(increase(graphql_queries_errors{instance=\"$instance\"}[$__range]) OR vector(0)) / sum(increase(graphql_queries_resolved{instance=\"$instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_errored{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_errored{instance=\"$instance\", operation=\"query\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Mutation Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_errored{instance=\"$instance\", operation=\"mutation\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation, operationName) (increase(graphql_queries_errored{instance=\"$instance\"}[$__range])) > 0"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Queries",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_resolved{instance=\"$instance\", operation=\"query\"}[$__range])) by (operationName) > 0"
    }
   ]
  },
  {
   "title": "Mutations",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_resolved{instance=\"$instance\", operation=\"mutation\"}[$__range])) by (operationName) > 0"
    }
   ]
  },
  {
   "title": "Total numbers of Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(graphql_queries_resolved{instance=\"$instance\", operation=\"query\"}[$__rate_interval])",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Total numbers of Mutations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(graphql_queries_resolved{instance=\"$instance\", operation=\"mutation\"}[$__rate_interval])",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Total numbers of field resolver requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(graphql_resolver_time_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{parentType}}.{{fieldName}} - {{returnType}}"
    }
   ]
  },
  {
   "title": "Average inbound field resolver duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(graphql_resolver_time_sum{instance=\"$instance\"}[$__rate_interval]) / rate(graphql_resolver_time_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{parentType}}.{{fieldName}} - {{returnType}}"
    }
   ]
  },
  { "title": "Field Resolvers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } }
 ]
}