global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.25:9090'] # Цель для сбора метрик самого Prometheus

  - job_name: 'myApp'
    static_configs:
      - targets: ['192.168.0.25:3010']
    metrics_path: /api/metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.0.25:8080']
