global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api:3010']
    metrics_path: /api/metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
