{
 "title": "Postgres",
 "description": "Счетчики базы данных",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Users",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM \"user\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "account",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM account LIMIT 50 "
    }
   ]
  },
  {
   "title": "GROUPS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM \"group\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Categories",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM category LIMIT 50 "
    }
   ]
  }
 ]
}