query getCart {
  getCart {
    items {
      id
      product {
        id
        model
        price
        name
        image
        optionName
        availableQuantity
      }
      quantity
      available
    }
    totalAmount
    discount
    total
    percentDiscount
    canCheckout
    messageError
  }
}
