query getMainPageBlocksOnlyTrue {
  getMainPageBlocksOnlyTrue {
    id
    name
    title
    link
    status
    products {
      id
      price
      quantity
      status
      sortOrder
      description {
        name
        description
      }
      images {
        image
        blurDataURL
      }
    }
  }
}
