mutation CreateOptionValues(
  $createOptionValueForOptionInput: CreateOptionValueForOptionInput!
) {
  createOptionValues(
    createOptionValueForOptionInput: $createOptionValueForOptionInput
  ) {
    id
    name
    sortOrder
    colorCode
  }
}
