mutation createUserAdmin($createUserAdminInput: SignUpUserInputDTO!) {
  createUserAdmin(createUserAdminInput: $createUserAdminInput) {
    id
    name
    phone
    email
    registrationDate
    lastLogin
    company {
      name
      inn
      kpp
      ogrn
      urAddress
      checkingAccount
      correspondentAccount
      bankName
      bikBank
      correspondentAccount
    }
  }
}
