mutation CreateOption($createOptionInput: CreateOptionInput!) {
  createOption(createOptionInput: $createOptionInput) {
    id
    name
    type
    sortOrder
    values {
      id
      name
      sortOrder
    }
  }
}
