query getAllInformations($pagination: OrdersPaginationAdminDTO!) {
  getAllInformations(pagination: $pagination) {
    data {
      id
      name
      title
      content
      status
    }
    total
  }
}
