query GetCategoryById($id: String!) {
  getCategoryById(id: $id) {
    id
    image
    parent_id
    sort_order
    status
    descriptions {
      id
      name
      description
      meta_title
      meta_h1
      meta_description
      meta_keyword
    }
    children {
      id
      image
      parent_id
      sort_order
      status
      descriptions {
        id
        name
        description
        meta_title
        meta_h1
        meta_description
        meta_keyword
      }
      children {
        id
        image
        parent_id
        sort_order
        status
        descriptions {
          id
          name
          description
          meta_title
          meta_h1
          meta_description
          meta_keyword
        }
      }
    }
  }
}
