query GetFeedbackById($input: FeedBackIdInput!) {
  getFeedbackById(input: $input) {
    id
    text
    status
    user {
      id
      name
      company {
        inn
        name
      }
    }
  }
}
